# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-14 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0004_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Answer',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='comment',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='comment_num',
            new_name='answer_num',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
