# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-26 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0007_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='column',
        ),
    ]
