# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-30 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0009_auto_20161130_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='collected_num',
            field=models.IntegerField(default=0),
        ),
    ]
