# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-30 10:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0010_userprofile_collected_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='com.Question')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='collected_num',
            new_name='keep_num',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='collected',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='keep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='com.Keep'),
        ),
    ]
