# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-30 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0011_auto_20161130_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='keep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='com.Keep'),
        ),
    ]
