# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-02 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0012_auto_20161130_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Intro',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='intro'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='em',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='em'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='job',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='job'),
        ),
    ]
