# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-04 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0015_auto_20161202_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='keep',
        ),
        migrations.AlterField(
            model_name='keep',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='com.UserProfile'),
        ),
    ]
