# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-05 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0017_auto_20161205_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keep',
            options={'verbose_name': 'created_on', 'verbose_name_plural': 'created_on'},
        ),
    ]
